### ISSUE TITLE
autofill/filter function not working on Bulk Editor "Detail" dropdown menu

### ISSUE THREAD

**Issue by SarahRDBingo** [mbari-org/vars-annotation#126]
trying to search within the possible details created in the dive for errors. Typing out the  Link name in the autofill does not narrow or filter out other details in the drop down list. Similar issues arise when trying to type out specific concepts for the link name in the "upon" detail popup window from the upon quick button. Autofill and filter function seems to freeze up when typing in field. Program seems to be fixed when rebooted.

**Comment by kwalz** [comment]
@rissalemon @lonnylundsten I see the upon button issue is listed here along with bulk editor issues that we also encounter. I think the upon button is fixed in 2.2.2, we are testing now but other issues are still outstanding.
