### ISSUE TITLE
Cannot create multiple frame grabs within 1/sec

### ISSUE THREAD

**Issue by nikkicunanan** [mbari-org/vars-annotation#137]
- Cannot create multiple frame grab within 1/sec.
- Created a frame grab, removed from VARS annotation because it was not ideal (blurry). Attempted to create a new frame grab a few frames away from original frame grab, but VARS produced an error.
- Original frame grab created still exists, but it seems VARS is still trying to name a *new* frame grab the same name as the original because the new frame was created within the same second.

**Comment by hohonuuli** [comment]
@nikkicunanan Ah yes .. thanks for the heads up. I've added microseconds to the name. I'll run tests today to see if any downstream processing get's broken. This should be pushed out in a new release in a few days.

**Comment by nikkicunanan** [comment]
@hohonuuli Mahalo Brian! We appreciate it.

**Comment by hohonuuli** [comment]
Added this fix to https://github.com/mbari-media-management/vars-annotation/releases/tag/1.4.0-rc2 for you to try out.

**Comment by lonnylundsten** [comment]
I believe this is fixed, closing.
