### ISSUE TITLE
adding comments to captured frame grabs

### ISSUE THREAD

**Issue by kakanikatija** [mbari-org/vars-annotation#140]
when selecting the add comment button, the comment popup window emerges, but you still have to mouse over to the comment box field and click before typing. would be good to automatically do that since that's the whole point of adding a comment

**Comment by kakanikatija** [comment]
Hi Brian! muauauajhah

**Comment by kakanikatija** [comment]
Text field should have focus

**Comment by lonnylundsten** [comment]
Closing as issue is addressed elsewhere: > Related to [mbari-org/vars-feedback#73](https://github.com/mbari-org/vars-feedback/issues/73)
