### ISSUE TITLE
m3-quickstart vars_build.sh fails

### ISSUE THREAD

**Issue by duane-edgington** [mbari-org/vars-annotation#149]
Hi. I am trying to build vars on my M1 Mac. I have successfully gone through these steps:
# Get setup
git clone git@github.com:mbari-media-management/m3-quickstart.git
cd m3-quickstart

# Start the web server, database, and VARS services
# The first time it's run it takes a while. Be patient.
bin/docker_start.sh

# Builds some custom VARS apps under temp/apps
# You need GITHUB_TOKEN and GITHUB_USERNAME environment variables set.
#   see https://github.com/mbari-org/maven#gradle
export GITHUB_TOKEN=<your github token>
export GITHUB_USERNAME=<your github username>

However, at this step
bin/vars_build.sh

I get a fatal error 
(base) duane@ICEFISH m3-quickstart % bin/vars_build.sh                                                                                 
--- BUILDING VARS Knowledgebase Application
Base Directory:      /Users/duane/m3-quickstart/bin
HOST:                http://134.89.11.109
ANNOSAURUS REST URL: http://134.89.11.109:8082/anno/v1
KB JDBC URL:         jdbc:postgresql://134.89.11.109:5432/M3_VARS?sslmode=disable&stringType=unspecified
Deleting existing repo at /Users/duane/m3-quickstart/temp/repos/vars-kb
Building vars-kb in /Users/duane/m3-quickstart/temp/repos/vars-kb
Cloning into 'vars-kb'...
remote: Enumerating objects: 2438, done.
remote: Counting objects: 100% (226/226), done.
remote: Compressing objects: 100% (146/146), done.
remote: Total 2438 (delta 88), reused 172 (delta 54), pack-reused 2212
Receiving objects: 100% (2438/2438), 3.58 MiB | 9.89 MiB/s, done.
Resolving deltas: 100% (1186/1186), done.
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Configure project :
Found module name 'org.mbari.kb.core'
Jdeps Gradle plugin 0.12.0. Consider becoming a patron at https://www.patreon.com/aalmiray
Found module name 'org.mbari.kb.jpa'
Found module name 'org.mbari.kb.shared'
Found module name 'org.mbari.kb.ui'

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/duane/m3-quickstart/temp/repos/vars-kb/org.mbari.kb.core/build.gradle'

* What went wrong:
Could not compile build file '/Users/duane/m3-quickstart/temp/repos/vars-kb/org.mbari.kb.core/build.gradle'.
> startup failed:
  General error during conversion: Unsupported class file major version 63
  
What should I do now?

**Comment by hohonuuli** [comment]
@duane-edgington Thanks for the heads up. It looks like I've compiled one of the dependencies using Java 19 by accident. (I'll have to sort out which one and make a change). In the meantime, you could try building using Java 19 instead. However, gradle is really snotty about Java versions. So your mileage may vary, I'll try to sort out the misbehaving dependency later today.

**Comment by hohonuuli** [comment]
Oh, I misspoke. You may be trying to build with Java 19 and gradle is complaining. I can upgrade the gradlew version in the VARS kb. Give me a few minutes.

**Comment by hohonuuli** [comment]
@duane-edgington Give it another try.

**Comment by duane-edgington** [comment]
Thanks Brian. I have Java 19 installed from OpenJDK. Or do I need the official Oracle commercially licensed JDK 19?? Or should I be running a different version of Java?? 

Duane

**Comment by duane-edgington** [comment]
Trying now. It is progressing… 

It throws a lot of EL Severe messages at 

Task :org.mbari.kb.jpa:performJPAWeaving 
throws warnings at 

Task :createDelegatingModules 




And ends with 

BUILD SUCCESSFUL in 1m 6s 

10 actionable tasks: 10 executed 




So you can probably close the ticket… 




thanks 




Duane

**Comment by NancyJS** [comment]
@hohonuuli Can we close this?

**Comment by lonnylundsten** [comment]
> @hohonuuli Can we close this?
