### ISSUE TITLE
Some changes made via the bulk editor are not updating the table view

### ISSUE THREAD

**Issue by hohonuuli** [mbari-org/vars-annotation#155]
I talked to Larissa. She mention that she change group/activity in the bulk editor. The changes were made in the database but they table wasn't refreshed to reflect those changes. This issue occurs in [version 1.5.0](https://github.com/mbari-media-management/vars-annotation/releases/tag/1.5.0)

**Comment by hohonuuli** [comment]
Related to mbari-org/vars-feedback#71 and mbari-org/vars-feedback#72

**Comment by hohonuuli** [comment]
Fixed in https://github.com/mbari-org/vars-annotation/releases/tag/2.1.3

**Comment by kwalz** [comment]
@hohonuuli Sarah Bingo's issue is this one that we are still having as well, table doesn't update with the changes. 
https://github.com/mbari-org/vars-feedback/issues/136#issuecomment-2649079989
