### ISSUE TITLE
Create `add localization` button

### ISSUE THREAD

**Issue by hohonuuli** [mbari-org/vars-annotation#164]
This button will add a localization to an existing annotation. The annotation must:

1. Meet be on a video with same start/duration/dimensions as currently opened video.
2. Not have an existing localization

When pressed a new localization will be put in the center of the video. Dimensions are TBD

**Comment by lonnylundsten** [comment]
This is being tracked in a another issue in the vars-feedback GitHub so I am closing this one, which is less descriptive.

**Comment by hohonuuli** [comment]
Duplicae of #183
