### ISSUE TITLE
Investigate lag with DARC's VARS System

### ISSUE THREAD

**Issue by hohonuuli** [mbari-org/vars-annotation#165]
From @MeaganPutts: 

> [...] it is extremely laggy when creating or changing records and sometimes does not make the changes that I have entered in the editing pane. Also, it is exhibiting odd behavior; often when I try to move backward through the video or skip to timecode the video will freeze for some time and when I click on a record with an image the image will not show. If I wait and/or click around on other records, things will be start working again.

@MeaganPutts, a few things to help me sleuth this:

1. Do these things happen all the time or do they come and go?
2. Are the video files copied to the machine you are annotating on?
3. The next time these things occur can you go to the hidden directory in your home directory at `~/.vars/logs` and send me the most recent log file?

From your description is sounds like network lag of some sort. But not sure what the source is yet.

**Comment by hohonuuli** [comment]
I've change the logging level used by all service to INFO (from DEBUG) and restarted DARCs services. The logs were getting very large, that might have had an impact on performance.

**Comment by MeaganPutts** [comment]
1. The lag comes and goes. It always freezes when trying to go backwards
through a video. (This never happened on any previous version).
2. The Video is on the server or an external drive on the machine itself.

**Comment by hohonuuli** [comment]
Which version of Sharktopoda are you using?

**Comment by MeaganPutts** [comment]
Original 1.0.1. Is there a better version?
