### ISSUE TITLE
T536, T537, & T538 are co-mingled

### ISSUE THREAD

**Issue by KSchlining** [mbari-org/vars-annotation#168]
It looks like T536 was merged with the log for T537. Can we re-merge it with the correct log file? There are no annotations for T537 but all the annotations for T536 & T538 are in VARS under that dive #.
Reported previously in JIRA #VARS-626 and #VARS-741.
Also, the metadata for the video resolution for the T536 files is showing up as HD instead of SD when  browsing to the files in the VAM.

**Comment by hohonuuli** [comment]
Links to JIRA issues:
- https://mbari1.atlassian.net/browse/VARS-626
- https://mbari1.atlassian.net/browse/VARS-741

**Comment by hohonuuli** [comment]
Sanity checks. Here's the URLs to inspect the video assets for the dives:

- http://m3.shore.mbari.org/vam/v1/videosequences/name/Tiburon%200536
- http://m3.shore.mbari.org/vam/v1/videosequences/name/Tiburon%200537
- http://m3.shore.mbari.org/vam/v1/videosequences/name/Tiburon%200538

The video tapes for all 3 dives are all in `Tiburon -537`

**Comment by hohonuuli** [comment]
Proposed Fix for T0536. Tested on fog server:

```sql
UPDATE videos SET video_sequence_uuid = '67282c6d-adda-4d79-9726-7fbbd6a0caaa'
WHERE video_sequence_uuid = '9b614cca-3e6b-4aa7-ae48-2967cb4ab35f' AND name LIKE 'T0536-%'
```

**Comment by hohonuuli** [comment]
Proposed fix for T0538. Tested on fog server:

```sql
UPDATE videos SET video_sequence_uuid = '379ffa5b-c3fc-4c2e-9079-e6479685aada'
WHERE video_sequence_uuid = '9b614cca-3e6b-4aa7-ae48-29
```

**Comment by hohonuuli** [comment]
Output from fixes:

```text
[2023-12-12 11:16:29] Connected
M3_VIDEO_ASSETS> use M3_VIDEO_ASSETS
[2023-12-12 11:16:29] [S0001][5701] Changed database context to 'M3_VIDEO_ASSETS'.
[2023-12-12 11:16:29] completed in 11 ms
M3_VIDEO_ASSETS> UPDATE videos SET video_sequence_uuid = '67282c6d-adda-4d79-9726-7fbbd6a0caaa'
                 WHERE video_sequence_uuid = '9b614cca-3e6b-4aa7-ae48-2967cb4ab35f' AND name LIKE 'T0536-%'
[2023-12-12 11:16:29] 9 rows affected in 58 ms
```

```text
M3_VIDEO_ASSETS> UPDATE videos SET video_sequence_uuid = '379ffa5b-c3fc-4c2e-9079-e6479685aada'
                 WHERE video_sequence_uuid = '9b614cca-3e6b-4aa7-ae48-2967cb4ab35f' AND name LIKE 'T0538-%'
[2023-12-12 11:17:53] 9 rows affected in 11 ms
```

**Comment by hohonuuli** [comment]
Using the [m3-merge](https://bitbucket.org/mbari/m3-merge) project to correct the start timestamps and re-merge. Timestamps for the tape vide references have been corrected using:

```sh
cd m3-merge
sbt pack
cd target/pack/bin
mv ../conf/production.conf ../conf/application.conf
adjust_tape_timestamps "Tiburon" 536
adjust_tape_timestamps "Tiburon" 537
adjust_tape_timestamps "Tiburon" 538
```

**Comment by hohonuuli** [comment]
These dives have been remerged using:

```sh
merge_rov "Tiburon" 536
merge_rov "Tiburon" 537  # Does nothing as there's no new data to remerge
merge_rov "Tiburon" 538
```

**Comment by hohonuuli** [comment]
@KSchlining Everything should be good now. Take a look and let me know and I'll close the issue if all is well.

**Comment by kwalz** [comment]
@hohonuuli associated with this, see attached screenshot, can we edit the tape start and end parameters and/or duration parameters? Here this one says tape is duration 14 hours (dive was that long but not tape). We're seeing a lot of errors for tape start and end times and it is causing issues for new IMES files and old annotations. It may have to be a manual edit and I can take those on as I go through issue tapes.

<img width="1412" alt="Screenshot 2023-12-12 at 12 05 43 PM" src="https://github.com/mbari-org/vars-annotation/assets/34140155/192f5ff9-df41-451c-9d5d-6bf7e8bdc727">

**Comment by hohonuuli** [comment]
I think just opening the tape in VARS and then switching to another will fix the 536, 537, and 538 dives. But I'll double check.

**Comment by kwalz** [comment]
I think those tapes have dive start and end times instead of just tape duration :)

**Comment by hohonuuli** [comment]
@kwalz I've moved the issue regarding duration parameters to #85 as a separate issue. So just review the tape dimensions in this issue, so I can close it.

**Comment by hohonuuli** [comment]
Tapes only have start times and durations. The end time is calculated from those.

**Comment by lonnylundsten** [comment]
> @kwalz I've moved the issue regarding duration parameters to #85 as a separate issue. So just review the tape dimensions in this issue, so I can close it.

@kwalz @KSchlining Has this been fixed? OK to close this issue?

**Comment by kwalz** [comment]
T538 still has issues, I'll try to troubleshoot and report back here with more info, please keep this ticket open.

**Comment by kwalz** [comment]
Tapes are no longer co-mingled (fixed remaining ones with issues using ./adjust_tape_timestamps pessimistic and ./set-tape-time) but T537 and T538 SD tape assets are listed as 1920x1080 in registry — they are SD tapes so issue is related to issue #84, I made a comment there so will close this issue.
