### ISSUE TITLE
Refresh issue?

### ISSUE THREAD

**Issue by KSchlining** [mbari-org/vars-annotation#176]
Today was the first time I've seen this issue, but after I opened a new dive in VARS, it kept annotations from the previous dive I had been viewing. These 2 lines (from a 2017 dive) stayed even if I hit refresh and even when I opened another file in the 2019 dive. See frame grabs attached.
![D1168T163024_screenshot2024-03-22 at 4 31 32 PM](https://github.com/mbari-org/vars-annotation/assets/42750242/3856e3b5-6964-426c-8ec6-7f7d61d09a67)
![D1168T174525_screenshot2024-03-22 at 4 39 09 PM](https://github.com/mbari-org/vars-annotation/assets/42750242/f1a4fe62-3998-4910-8ea6-394ba035f26e)

**Comment by lonnylundsten** [comment]
@KSchlining Can you verify this is still an issue Kyra?

**Comment by KSchlining** [comment]
No, I don't believe I've seen that issue since the initial reporting. 

~K. 

~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~` 
Kyra Schlining 
Monterey Bay Aquarium Research Institute

**Comment by lonnylundsten** [comment]
Assuming this was a random issue, so closing.
