### ISSUE TITLE
Image Annotation Feature Requests

### ISSUE THREAD

**Issue by hohonuuli** [mbari-org/vars-annotation#48]
I'll be porting the image annotation features from the old VARS into the new VARS/M3 system. This issue is to track feature requests and improvements related to image annotation

**Comment by hohonuuli** [comment]
From Crissy ... #1 feature request is __zoom__.

**Comment by hohonuuli** [comment]
From Crissy:

> Along with the zoom, the ability to adjust brightness/contrast would be helpful in the next version of VARS.

**Comment by hohonuuli** [comment]
From Crissy:

> Is it possible to have two VARS windows running at once on a PC? Ken would like to compare images from two different video archives at the same time (images taken at the same time by two different cameras).

**Comment by chuffard** [comment]
Track an individual annotation across multiple frames.

**Comment by chuffard** [comment]
Add the ability to hide all annotations by other users.

**Comment by hohonuuli** [comment]
In progress. Related to #78

**Comment by hohonuuli** [comment]
see [Mondrian](https://github.com/mbari-org/mondrian)
