### ISSUE TITLE
UI hangs when opening video if Sharktopoda is not running

### ISSUE THREAD

**Issue by hohonuuli** [mbari-org/vars-annotation#5]
After opening a video in vars-annotation, the UI attempts to connect to Sharktopoda. If it's not found the UI hangs. The fix should be:

- Query Sharktopoda to see if it's running. 
    1. If running, open the video
    2. If not running, fall back to a JavaFX-based player.

**Comment by hohonuuli** [comment]
The video lab submitted this request:

> Have Sharktopoda open automagically when you open VARS.

**Comment by NancyJS** [comment]
@hohonuuli can this be closed?

**Comment by lonnylundsten** [comment]
> @hohonuuli can this be closed?

**Comment by lonnylundsten** [comment]
Verified this is not an issue on 9/20/2024. VARS does not hang when trying to open a video through either the finder method or the asset manager. Closing issue.
